/** Actions d'audit standardisées — toute action sensible doit utiliser une de ces clés */
export const AuditAction = {
  // Auth
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_PASSWORD_CHANGE: 'AUTH_PASSWORD_CHANGE',
  AUTH_REGISTER_TENANT: 'AUTH_REGISTER_TENANT',
  AUTH_REGISTER_ORG: 'AUTH_REGISTER_ORG',
  AUTH_TOKEN_REFRESH: 'AUTH_TOKEN_REFRESH',
  AUTH_TOKEN_REUSE: 'AUTH_TOKEN_REUSE',
  AUTH_PASSWORD_RESET_REQUEST: 'AUTH_PASSWORD_RESET_REQUEST',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  AUTH_SESSION_REVOKE: 'AUTH_SESSION_REVOKE',
  AUTH_MFA_SETUP: 'AUTH_MFA_SETUP',
  AUTH_MFA_ENABLE: 'AUTH_MFA_ENABLE',
  AUTH_MFA_DISABLE: 'AUTH_MFA_DISABLE',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  INVITE_CREATE: 'INVITE_CREATE',
  INVITE_ACCEPT: 'INVITE_ACCEPT',
  INVITE_REVOKE: 'INVITE_REVOKE',

  // Candidatures
  APPLICATION_DRAFT_CREATE: 'APPLICATION_DRAFT_CREATE',
  APPLICATION_DRAFT_UPDATE: 'APPLICATION_DRAFT_UPDATE',
  APPLICATION_SUBMIT: 'APPLICATION_SUBMIT',
  APPLICATION_WITHDRAW: 'APPLICATION_WITHDRAW',
  APPLICATION_APPROVE: 'APPLICATION_APPROVE',
  APPLICATION_REJECT: 'APPLICATION_REJECT',

  // Utilisateurs
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ROLE_CHANGE: 'USER_ROLE_CHANGE',
  USER_ACTIVATE: 'USER_ACTIVATE',
  USER_DEACTIVATE: 'USER_DEACTIVATE',

  // Organisation plateforme
  ORG_ACTIVATE: 'ORG_ACTIVATE',
  ORG_DEACTIVATE: 'ORG_DEACTIVATE',
  ORG_VALIDATE: 'ORG_VALIDATE',

  // Immeubles
  BUILDING_CREATE: 'BUILDING_CREATE',
  BUILDING_UPDATE: 'BUILDING_UPDATE',
  BUILDING_DELETE: 'BUILDING_DELETE',

  // Appartements
  APARTMENT_CREATE: 'APARTMENT_CREATE',
  APARTMENT_UPDATE: 'APARTMENT_UPDATE',
  APARTMENT_DELETE: 'APARTMENT_DELETE',
  APARTMENT_BULK_CREATE: 'APARTMENT_BULK_CREATE',

  // Locataires
  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_UPDATE: 'TENANT_UPDATE',
  TENANT_DELETE: 'TENANT_DELETE',

  // Baux
  LEASE_CREATE: 'LEASE_CREATE',
  LEASE_UPDATE: 'LEASE_UPDATE',
  LEASE_RENEW: 'LEASE_RENEW',
  LEASE_SIGN: 'LEASE_SIGN',
  LEASE_TERMINATE: 'LEASE_TERMINATE',
  LEASE_EXPORT_PDF: 'LEASE_EXPORT_PDF',

  // Paiements
  PAYMENT_CREATE: 'PAYMENT_CREATE',
  PAYMENT_VALIDATE: 'PAYMENT_VALIDATE',
  PAYMENT_EXPORT_PDF: 'PAYMENT_EXPORT_PDF',
  PAYMENT_EXPORT_EXCEL: 'PAYMENT_EXPORT_EXCEL',

  // États des lieux
  INSPECTION_CREATE: 'INSPECTION_CREATE',
  INSPECTION_UPDATE: 'INSPECTION_UPDATE',
  INSPECTION_SIGN: 'INSPECTION_SIGN',
  INSPECTION_DELETE: 'INSPECTION_DELETE',

  // Centre de notifications
  MESSAGE_SEND: 'MESSAGE_SEND',
  REMINDER_SEND: 'REMINDER_SEND',
  TASK_CREATE: 'TASK_CREATE',
  TASK_COMPLETE: 'TASK_COMPLETE',

  // Maintenance
  MAINTENANCE_CREATE: 'MAINTENANCE_CREATE',
  MAINTENANCE_UPDATE: 'MAINTENANCE_UPDATE',
  MAINTENANCE_ASSIGN: 'MAINTENANCE_ASSIGN',
  MAINTENANCE_CLOSE: 'MAINTENANCE_CLOSE',
  PORTAL_MAINTENANCE_CREATE: 'PORTAL_MAINTENANCE_CREATE',

  // Annonces & documents
  LISTING_PUBLISH: 'LISTING_PUBLISH',
  LISTING_UNPUBLISH: 'LISTING_UNPUBLISH',
  DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
  DOCUMENT_DELETE: 'DOCUMENT_DELETE',

  // Rapports & exports
  REPORT_EXPORT: 'REPORT_EXPORT',
  AUDIT_EXPORT: 'AUDIT_EXPORT',

  // Abonnement & fonctionnalités
  SUBSCRIPTION_CHANGE: 'SUBSCRIPTION_CHANGE',
  SUBSCRIPTION_CANCEL: 'SUBSCRIPTION_CANCEL',
  SUBSCRIPTION_REACTIVATE: 'SUBSCRIPTION_REACTIVATE',
  FEATURE_ENABLE: 'FEATURE_ENABLE',
  FEATURE_DISABLE: 'FEATURE_DISABLE',

  // IA
  AI_SCORE: 'AI_SCORE',
  AI_USE: 'AI_USE',

  // Automatisation (n8n / cron)
  AUTOMATION_JOB_RUN: 'AUTOMATION_JOB_RUN',
} as const;

export type AuditActionKey = (typeof AuditAction)[keyof typeof AuditAction];
